# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'giao_dien_chinh.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pop_up import Ui_pop_up


class Ui_giao_dien_chinh(object):
    def setupUi(self, giao_dien_chinh):
        self.giao_dien_chinh = giao_dien_chinh
        giao_dien_chinh.setObjectName("giao_dien_chinh")
        giao_dien_chinh.resize(284, 214)
        font = QtGui.QFont()
        font.setUnderline(False)
        giao_dien_chinh.setFont(font)
        giao_dien_chinh.setFrameShape(QtWidgets.QFrame.StyledPanel)
        giao_dien_chinh.setFrameShadow(QtWidgets.QFrame.Raised)
        self.formLayout = QtWidgets.QFormLayout(giao_dien_chinh)
        self.formLayout.setObjectName("formLayout")
        self.button_layout = QtWidgets.QVBoxLayout()
        self.button_layout.setObjectName("button_layout")
        self.soan_cau_hoi_button = QtWidgets.QPushButton(giao_dien_chinh)
        self.soan_cau_hoi_button.setObjectName("soan_cau_hoi_button")
        self.button_layout.addWidget(self.soan_cau_hoi_button)
        self.xay_dung_de_button = QtWidgets.QPushButton(giao_dien_chinh)
        self.xay_dung_de_button.setObjectName("xay_dung_de_button")
        self.button_layout.addWidget(self.xay_dung_de_button)
        self.lam_bai_thi = QtWidgets.QPushButton(giao_dien_chinh)
        self.lam_bai_thi.setObjectName("lam_bai_thi")
        self.button_layout.addWidget(self.lam_bai_thi)
        self.danh_gia_ket_qua_button = QtWidgets.QPushButton(giao_dien_chinh)
        self.danh_gia_ket_qua_button.setObjectName("danh_gia_ket_qua_button")
        self.button_layout.addWidget(self.danh_gia_ket_qua_button)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.button_layout)
        self.thiet_lap_label = QtWidgets.QLabel(giao_dien_chinh)
        self.thiet_lap_label.setEnabled(True)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.thiet_lap_label.setFont(font)
        self.thiet_lap_label.setAutoFillBackground(False)
        self.thiet_lap_label.setObjectName("thiet_lap_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.thiet_lap_label)
        self.thoat_button = QtWidgets.QPushButton(giao_dien_chinh)
        self.thoat_button.setObjectName("thoat_button")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.thoat_button)

        self.pop_up = QtWidgets.QFrame()
        Ui_pop_up().set_up_pop_up_ui(self.pop_up)


        self.retranslateUi(giao_dien_chinh)
        self.soan_cau_hoi_button.clicked.connect(self.show_pop_up)
        self.xay_dung_de_button.clicked.connect(self.show_pop_up)
        self.lam_bai_thi.clicked.connect(self.show_pop_up)
        self.danh_gia_ket_qua_button.clicked.connect(self.show_pop_up)
        self.thoat_button.clicked.connect(giao_dien_chinh.close)
        QtCore.QMetaObject.connectSlotsByName(giao_dien_chinh)

    def retranslateUi(self, giao_dien_chinh):
        _translate = QtCore.QCoreApplication.translate
        giao_dien_chinh.setWindowTitle(_translate("giao_dien_chinh", "Frame"))
        self.soan_cau_hoi_button.setText(_translate("giao_dien_chinh", "Soạn câu hỏi"))
        self.xay_dung_de_button.setText(_translate("giao_dien_chinh", "Xây dựng đề "))
        self.lam_bai_thi.setText(_translate("giao_dien_chinh", "Làm bài thi"))
        self.danh_gia_ket_qua_button.setText(_translate("giao_dien_chinh", "Đánh giá kết quả"))
        self.thiet_lap_label.setText(_translate("giao_dien_chinh", "<html><head/><body><p><span style=\" color:#0000ff;\">Thiết lập</span></p></body></html>"))
        self.thoat_button.setText(_translate("giao_dien_chinh", "Thoát"))

    def show_pop_up(self):
        pop_up_ui = Ui_pop_up()
        print(pop_up_ui)
        self.pop_up.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    giao_dien_chinh = QtWidgets.QFrame()
    giao_dien_chinh_ui = Ui_giao_dien_chinh()
    giao_dien_chinh_ui.setupUi(giao_dien_chinh)
    giao_dien_chinh.show()
    sys.exit(app.exec_())
