# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pop_up.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pop_up(object):
    def set_up_pop_up_ui(self, pop_up):
        pop_up.setObjectName("pop_up")
        pop_up.resize(424, 249)
        pop_up.setFrameShape(QtWidgets.QFrame.StyledPanel)
        pop_up.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chon_mon_hoc_label = QtWidgets.QLabel(pop_up)
        self.chon_mon_hoc_label.setGeometry(QtCore.QRect(40, 20, 111, 16))
        self.chon_mon_hoc_label.setObjectName("chon_mon_hoc_label")
        self.danh_sach_mon_hoc_label = QtWidgets.QLabel(pop_up)
        self.danh_sach_mon_hoc_label.setGeometry(QtCore.QRect(40, 50, 141, 16))
        self.danh_sach_mon_hoc_label.setObjectName("danh_sach_mon_hoc_label")
        self.danh_sach_mon_hoc_combo_box = QtWidgets.QComboBox(pop_up)
        self.danh_sach_mon_hoc_combo_box.setGeometry(QtCore.QRect(30, 90, 104, 26))
        self.danh_sach_mon_hoc_combo_box.setObjectName("danh_sach_mon_hoc_combo_box")
        self.danh_sach_mon_hoc_combo_box.addItem("")
        self.danh_sach_mon_hoc_combo_box.addItem("")
        self.danh_sach_mon_hoc_combo_box.addItem("")
        self.quan_li_mon_hoc_label = QtWidgets.QLabel(pop_up)
        self.quan_li_mon_hoc_label.setGeometry(QtCore.QRect(220, 100, 121, 21))
        self.quan_li_mon_hoc_label.setObjectName("quan_li_mon_hoc_label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(pop_up)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(150, 130, 228, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("dang_cau_hoi_horizontal_layout")
        self.ok_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ok_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ok_button.sizePolicy().hasHeightForWidth())
        self.ok_button.setSizePolicy(sizePolicy)
        self.ok_button.setObjectName("ok_button")
        self.horizontalLayout.addWidget(self.ok_button)
        self.cancel_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)

        self.retranslateUi(pop_up)
        QtCore.QMetaObject.connectSlotsByName(pop_up)

    def retranslateUi(self, pop_up):
        _translate = QtCore.QCoreApplication.translate
        pop_up.setWindowTitle(_translate("pop_up", "Frame"))
        self.chon_mon_hoc_label.setText(_translate("pop_up", "Chọn môn học:"))
        self.danh_sach_mon_hoc_label.setText(_translate("pop_up", "Danh sách môn học"))
        self.danh_sach_mon_hoc_combo_box.setItemText(0, _translate("pop_up", "hey"))
        self.danh_sach_mon_hoc_combo_box.setItemText(1, _translate("pop_up", "yo"))
        self.danh_sach_mon_hoc_combo_box.setItemText(2, _translate("pop_up", "nigngen"))
        self.quan_li_mon_hoc_label.setText(_translate("pop_up", "Quản lí môn học"))
        self.ok_button.setText(_translate("pop_up", "OK"))
        self.cancel_button.setText(_translate("pop_up", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    pop_up = QtWidgets.QFrame()
    ui = Ui_pop_up()
    ui.set_up_pop_up_ui(pop_up)
    pop_up.show()
    sys.exit(app.exec_())
