# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chon_cau_hoi_dua_vao_de_thi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from database.Question.question_access import get_info, get_tu_luan_info, get_trac_nghiem_info, get_question_chapter
from database.Question.question_access import get_question_id, get_question_difficulty
from database.MCQS_Answer.mcqs_access import get_answer, get_right_answer
from PyQt5 import QtCore, QtGui, QtWidgets


class ui_chon_cau_hoi_dua_vao_de_thi_frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(971, 663)
        Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.question_list_widget = QtWidgets.QListWidget(Frame)
        self.question_list_widget.setGeometry(QtCore.QRect(40, 60, 301, 191))
        self.question_list_widget.setObjectName("question_list_widget")
        self.question_show_text_edit = QtWidgets.QTextEdit(Frame)
        self.question_show_text_edit.setGeometry(QtCore.QRect(370, 60, 411, 191))
        self.question_show_text_edit.setObjectName("question_show_text_edit")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 280, 261, 21))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tat_ca_radio_button = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.tat_ca_radio_button.setObjectName("tat_ca_radio_button")
        self.horizontalLayout.addWidget(self.tat_ca_radio_button)
        self.trac_nghiem_radio_button = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.trac_nghiem_radio_button.setObjectName("trac_nghiem_radio_button")
        self.horizontalLayout.addWidget(self.trac_nghiem_radio_button)
        self.tu_luan_radio_button = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.tu_luan_radio_button.setObjectName("tu_luan_radio_button")
        self.horizontalLayout.addWidget(self.tu_luan_radio_button)
        self.dang_cau_hoi_label = QtWidgets.QLabel(Frame)
        self.dang_cau_hoi_label.setGeometry(QtCore.QRect(50, 260, 79, 15))
        self.dang_cau_hoi_label.setObjectName("dang_cau_hoi_label")
        self.them_vao_de_thi_button = QtWidgets.QPushButton(Frame)
        self.them_vao_de_thi_button.setGeometry(QtCore.QRect(610, 270, 161, 41))
        self.them_vao_de_thi_button.setObjectName("them_vao_de_thi_button")
        self.exam_question_list_widget = QtWidgets.QListWidget(Frame)
        self.exam_question_list_widget.setGeometry(QtCore.QRect(30, 350, 301, 251))
        self.exam_question_list_widget.setObjectName("exam_question_list_widget")
        self.exam_show_text_edit = QtWidgets.QTextEdit(Frame)
        self.exam_show_text_edit.setGeometry(QtCore.QRect(370, 350, 401, 251))
        self.exam_show_text_edit.setObjectName("exam_show_text_edit")
        self.danh_sach_cau_hoi_label = QtWidgets.QLabel(Frame)
        self.danh_sach_cau_hoi_label.setGeometry(QtCore.QRect(50, 20, 161, 21))
        self.danh_sach_cau_hoi_label.setObjectName("danh_sach_cau_hoi_label")
        self.danh_sach_cac_cau_trong_de_label = QtWidgets.QLabel(Frame)
        self.danh_sach_cac_cau_trong_de_label.setGeometry(QtCore.QRect(40, 300, 311, 31))
        self.danh_sach_cac_cau_trong_de_label.setObjectName("danh_sach_cac_cau_trong_de_label")

        self.trac_nghiem_radio_button.clicked.connect(self.trac_nghiem_button_click)
        self.tu_luan_radio_button.clicked.connect(self.tu_luan_button_click)
        self.tat_ca_radio_button.clicked.connect(self.tat_ca_button_click)
        self.them_vao_de_thi_button.clicked.connect(self.them_vao_de_thi_button_click)

        self.question_list_widget.currentRowChanged.connect(self.question_list_widget_row_change)
        self.exam_question_list_widget.currentRowChanged.connect(self.exam_question_list_widget_row_change)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.question_show_text_edit.setHtml(_translate("Frame",
                                                        "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                        "p, li { white-space: pre-wrap; }\n"
                                                        "</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
                                                        "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tat_ca_radio_button.setText(_translate("Frame", "Tất cả"))
        self.trac_nghiem_radio_button.setText(_translate("Frame", "Trắc nghiệm"))
        self.tu_luan_radio_button.setText(_translate("Frame", "Tự luận"))
        self.dang_cau_hoi_label.setText(_translate("Frame", "Dạng câu hỏi"))
        self.them_vao_de_thi_button.setText(_translate("Frame", "Thêm vào đề thi"))
        self.exam_show_text_edit.setHtml(_translate("Frame",
                                                    "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                    "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                    "p, li { white-space: pre-wrap; }\n"
                                                    "</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
                                                    "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.danh_sach_cau_hoi_label.setText(_translate("Frame",
                                                        "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Danh sách câu hỏi</span></p></body></html>"))
        self.danh_sach_cac_cau_trong_de_label.setText(_translate("Frame",
                                                                 "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Danh sách các câu trong đề</span></p></body></html>"))

    def trac_nghiem_button_click(self):
        self.question_list_widget.clear()
        for i in get_trac_nghiem_info():
            self.question_list_widget.addItem(QtWidgets.QListWidgetItem(i))

    def tu_luan_button_click(self):
        self.question_list_widget.clear()
        for i in get_tu_luan_info():
            self.question_list_widget.addItem(QtWidgets.QListWidgetItem(i))

    def tat_ca_button_click(self):
        self.question_list_widget.clear()
        for i in get_info():
            self.question_list_widget.addItem(QtWidgets.QListWidgetItem(i))

    def them_vao_de_thi_button_click(self):
        question = self.question_list_widget.currentItem().text()
        self.exam_question_list_widget.addItem(question)
        self.exam_question_list_widget_row_change()

    def question_list_widget_row_change(self):
        try:
            self.question_show_text_edit.clear()
            question = self.question_list_widget.currentItem().text()
            question_id = get_question_id(question)
            list_answer = get_answer(question_id)
            self.question_show_text_edit.append(question)
            for number, answer in enumerate(list_answer):
                self.question_show_text_edit.append("{}.  {}".format(number, answer))
            self.question_show_text_edit.append("Thông tin chi tiết:")
            self.question_show_text_edit.append("Đáp án đúng: {}".format(get_right_answer(question_id)))
            self.question_show_text_edit.append("Độ khó: {}".format(get_question_difficulty(question_id)))
            self.question_show_text_edit.append("Chương: Chương {}".format(get_question_chapter(question_id)))

        except AttributeError:
            print("Attribute Error")
            pass

    def exam_question_list_widget_row_change(self):
        print("detect row change")
        questions = [self.exam_question_list_widget.item(x).text()
                     for x in range(self.exam_question_list_widget.count())]
        self.exam_show_text_edit.clear()
        alphabet = "ABCDEFGH"
        for number, question in enumerate(questions):
            question_id = get_question_id(question)
            self.exam_show_text_edit.append("Câu {}: {}".format(number + 1, question))
            for order, answer in enumerate(get_answer(question_id)):
                self.exam_show_text_edit.append("{}.   {}".format(alphabet[order], answer))
            self.exam_show_text_edit.append("")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = ui_chon_cau_hoi_dua_vao_de_thi_frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
