# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quan_li_de_thi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(769, 509)
        Frame.setAutoFillBackground(False)
        Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.quan_li_de_thi_label = QtWidgets.QLabel(Frame)
        self.quan_li_de_thi_label.setGeometry(QtCore.QRect(20, 10, 291, 51))
        self.quan_li_de_thi_label.setObjectName("quan_li_de_thi_label")
        self.mo_de_thi_co_san_label = QtWidgets.QLabel(Frame)
        self.mo_de_thi_co_san_label.setGeometry(QtCore.QRect(30, 60, 151, 41))
        self.mo_de_thi_co_san_label.setObjectName("mo_de_thi_co_san_label")
        self.tao_de_thi_moi_button = QtWidgets.QPushButton(Frame)
        self.tao_de_thi_moi_button.setGeometry(QtCore.QRect(500, 30, 151, 41))
        self.tao_de_thi_moi_button.setStyleSheet("background-color: blue;\n"
"color: white;\n"
"border-radius: 5px;")
        self.tao_de_thi_moi_button.setObjectName("tao_de_thi_moi_button")
        self.ngan_hang_de_thi_frame = QtWidgets.QWidget(Frame)
        self.ngan_hang_de_thi_frame.setGeometry(QtCore.QRect(20, 100, 721, 391))
        self.ngan_hang_de_thi_frame.setStyleSheet(".QWidget  {border-style: dashed;\n"
"border-width: 5px;\n"
"border-color: grey;}")
        self.ngan_hang_de_thi_frame.setObjectName("ngan_hang_de_thi_frame")
        self.de_thi_button = QtWidgets.QPushButton(self.ngan_hang_de_thi_frame)
        self.de_thi_button.setGeometry(QtCore.QRect(10, 20, 221, 121))
        self.de_thi_button.setStyleSheet("background-image : url(./canvas_background.jpeg);")
        self.de_thi_button.setObjectName("de_thi_button")
        self.de_thi_button_2 = QtWidgets.QPushButton(self.ngan_hang_de_thi_frame)
        self.de_thi_button_2.setGeometry(QtCore.QRect(240, 20, 221, 121))
        self.de_thi_button_2.setStyleSheet("background-image : url(./canvas_background.jpeg);")
        self.de_thi_button_2.setObjectName("de_thi_button_2")
        self.de_thi_button_3 = QtWidgets.QPushButton(self.ngan_hang_de_thi_frame)
        self.de_thi_button_3.setGeometry(QtCore.QRect(480, 20, 221, 121))
        self.de_thi_button_3.setStyleSheet("background-image : url(./canvas_background.jpeg);")
        self.de_thi_button_3.setObjectName("de_thi_button_3")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.quan_li_de_thi_label.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:24pt;\">Quản lý đề thi</span></p></body></html>"))
        self.mo_de_thi_co_san_label.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:18pt;\">Mở đề thi có sẵn</span></p></body></html>"))
        self.tao_de_thi_moi_button.setText(_translate("Frame", "Tạo đề thi mới"))
        self.de_thi_button.setText(_translate("Frame", "PushButton"))
        self.de_thi_button_2.setText(_translate("Frame", "PushButton"))
        self.de_thi_button_3.setText(_translate("Frame", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
