# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tu_luan.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1440, 767)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(250, 130, 291, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label.setObjectName("label")
        self.question_input = QtWidgets.QTextEdit(Dialog)
        self.question_input.setGeometry(QtCore.QRect(340, 200, 371, 161))
        self.question_input.setObjectName("textEdit")
        self.answer_input = QtWidgets.QTextEdit(Dialog)
        self.answer_input.setGeometry(QtCore.QRect(340, 430, 371, 81))
        self.answer_input.setObjectName("answer_input")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(290, 370, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(30)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.submit_button = QtWidgets.QPushButton(Dialog)
        self.submit_button.clicked.connect(self.submit)
        self.submit_button.setGeometry(QtCore.QRect(500, 550, 141, 41))
        self.submit_button.setObjectName("submit_button")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(260, 30, 561, 81))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.subject_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.subject_label.setObjectName("subject_label")
        self.horizontalLayout.addWidget(self.subject_label)
        self.subject_input = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.subject_input.setObjectName("subject_input")
        self.horizontalLayout.addWidget(self.subject_input)
        self.chapter_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.chapter_label.setObjectName("chapter_label")
        self.horizontalLayout.addWidget(self.chapter_label)
        self.chapter_spinbox = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.chapter_spinbox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.chapter_spinbox)
        self.difficulty_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.difficulty_label.setObjectName("difficulty_label")
        self.horizontalLayout.addWidget(self.difficulty_label)
        self.difficulty_spinbox = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.difficulty_spinbox.setObjectName("difficulty_spinbox")
        self.horizontalLayout.addWidget(self.difficulty_spinbox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Nhập vào câu hỏi"))
        self.label_2.setText(_translate("Dialog", "Nhập vào gợi ý"))
        self.submit_button.setText(_translate("Dialog", "Tạo câu hỏi"))
        self.subject_label.setText(_translate("Dialog", "Môn"))
        self.chapter_label.setText(_translate("Dialog", "Chương"))
        self.difficulty_label.setText(_translate("Dialog", "Độ khó"))

    def submit(self):
        print("subject is:")
        subject = self.subject_input.toPlainText()
        print(subject)
        print("chapter is:")
        chapter = self.chapter_spinbox.text()
        print(chapter)
        print("difficulty is: ")
        difficulty = self.difficulty_spinbox.text()
        print(difficulty)
        print("the question is: ")
        question = self.question_input.toPlainText()
        print(question)
        print("the answer is: ")
        answer = self.answer_input.toPlainText()
        print(answer)
        self.question_input.clear()
        self.answer_input.clear()
        self.subject_input.clear()
        self.question_input.setFocus()
        with open('./tu_luan_database.txt', 'a') as f:
            f.write(subject + "," + chapter + "," + difficulty + "," + question + "," + answer + "\n")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
