# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quan_li_cau_hoi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from functools import partial
from PyQt5 import QtCore, QtWidgets
from database.database_access import get_subject_name, get_subject_info


class Ui_quan_ly_mon_hoc_frame(object):
    def setupUi(self, quan_ly_mon_hoc_frame):
        quan_ly_mon_hoc_frame.setObjectName("quan_ly_mon_hoc_frame")
        quan_ly_mon_hoc_frame.resize(763, 482)
        quan_ly_mon_hoc_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        quan_ly_mon_hoc_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalLayoutWidget = QtWidgets.QWidget(quan_ly_mon_hoc_frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(360, 50, 346, 301))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.ten_mon_hoc_text_edit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.ten_mon_hoc_text_edit.setObjectName("ten_mon_hoc_text_edit")
        self.horizontalLayout.addWidget(self.ten_mon_hoc_text_edit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.ma_hoc_phan_text_edit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.ma_hoc_phan_text_edit.setObjectName("ma_hoc_phan_text_edit")
        self.horizontalLayout_2.addWidget(self.ma_hoc_phan_text_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_3.addWidget(self.spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.gioi_thieu_text_edit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.gioi_thieu_text_edit.setObjectName("gioi_thieu_text_edit")
        self.horizontalLayout_4.addWidget(self.gioi_thieu_text_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.danh_sach_mon_hoc_label = QtWidgets.QLabel(quan_ly_mon_hoc_frame)
        self.danh_sach_mon_hoc_label.setGeometry(QtCore.QRect(50, 20, 151, 31))
        self.danh_sach_mon_hoc_label.setObjectName("danh_sach_mon_hoc_label")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(quan_ly_mon_hoc_frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(40, 100, 181, 311))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.so_mon_hoc_vertical_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.so_mon_hoc_vertical_layout.setContentsMargins(0, 0, 0, 0)
        self.so_mon_hoc_vertical_layout.setObjectName("so_mon_hoc_vertical_layout")

        for name in get_subject_name():
            subject_button = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
            subject_button.clicked.connect(lambda state, x=name: self.mon_hoc_click(x))
            self.so_mon_hoc_vertical_layout.addWidget(subject_button)
            subject_button.setText(name)

        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(quan_ly_mon_hoc_frame)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(250, 360, 352, 80))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.luu_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.luu_button.setObjectName("luu_button")
        self.horizontalLayout_5.addWidget(self.luu_button)
        self.huy_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.huy_button.setObjectName("huy_button")
        self.horizontalLayout_5.addWidget(self.huy_button)
        self.xoa_mon_hoc_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.xoa_mon_hoc_button.setObjectName("xoa_mon_hoc_button")
        self.horizontalLayout_5.addWidget(self.xoa_mon_hoc_button)

        self.retranslateUi(quan_ly_mon_hoc_frame)
        QtCore.QMetaObject.connectSlotsByName(quan_ly_mon_hoc_frame)

    def retranslateUi(self, quan_ly_mon_hoc_frame):
        _translate = QtCore.QCoreApplication.translate
        quan_ly_mon_hoc_frame.setWindowTitle(_translate("quan_ly_mon_hoc_frame", "Frame"))
        self.label.setText(_translate("quan_ly_mon_hoc_frame", "Tên môn học"))
        self.label_2.setText(_translate("quan_ly_mon_hoc_frame", "Mã học phần"))
        self.label_3.setText(_translate("quan_ly_mon_hoc_frame", "Số chương"))
        self.label_4.setText(_translate("quan_ly_mon_hoc_frame", "Giới thiệu"))
        self.danh_sach_mon_hoc_label.setText(_translate("quan_ly_mon_hoc_frame", "Danh sách môn học"))
        self.luu_button.setText(_translate("quan_ly_mon_hoc_frame", "Lưu"))
        self.huy_button.setText(_translate("quan_ly_mon_hoc_frame", "Hủy"))
        self.xoa_mon_hoc_button.setText(_translate("quan_ly_mon_hoc_frame", "Xóa môn học"))

    def mon_hoc_click(self, name):
        subject_info = get_subject_info(name)
        self.ten_mon_hoc_text_edit.setPlainText(name)
        self.ma_hoc_phan_text_edit.setPlainText(subject_info[0])
        self.gioi_thieu_text_edit.setPlainText(subject_info[2])



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    quan_ly_mon_hoc_frame = QtWidgets.QFrame()
    ui = Ui_quan_ly_mon_hoc_frame()
    ui.setupUi(quan_ly_mon_hoc_frame)
    quan_ly_mon_hoc_frame.show()
    sys.exit(app.exec_())
