# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'soan_cau_hoi_ver_trinh_thanh_trung.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QFrame

from database.Question.question_access import *
from database.MCQS_Answer.mcqs_access import *
from them_dap_an_pop_up import Ui_them_dap_an_pop_up
from chinh_sua_dap_an_pop_up import Ui_chinh_sua_dap_an_pop_up
from them_cau_hoi_pop_up import Ui_them_cau_hoi_pop_up


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(590, 558)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Frame.sizePolicy().hasHeightForWidth())
        Frame.setSizePolicy(sizePolicy)
        Frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        Frame.setAutoFillBackground(False)
        Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.danh_sach_cau_hoi_label = QtWidgets.QLabel(Frame)
        self.danh_sach_cau_hoi_label.setGeometry(QtCore.QRect(20, 20, 211, 31))
        self.danh_sach_cau_hoi_label.setObjectName("danh_sach_cau_hoi_label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(260, 20, 271, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.dang_cau_hoi_horizontal_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.dang_cau_hoi_horizontal_layout.setContentsMargins(0, 0, 0, 0)
        self.dang_cau_hoi_horizontal_layout.setObjectName("dang_cau_hoi_horizontal_layout")
        self.dang_cau_hoi_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.dang_cau_hoi_label.setObjectName("dang_cau_hoi_label")
        self.dang_cau_hoi_horizontal_layout.addWidget(self.dang_cau_hoi_label)
        self.trac_nghiem_radio_button = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.trac_nghiem_radio_button.setObjectName("trac_nghiem_radio_button")
        self.dang_cau_hoi_horizontal_layout.addWidget(self.trac_nghiem_radio_button)
        self.tu_luan_radio_button = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.tu_luan_radio_button.setObjectName("tu_luan_radio_button")
        self.dang_cau_hoi_horizontal_layout.addWidget(self.tu_luan_radio_button)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Frame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(260, 80, 251, 131))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.de_bai_horizontal_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.de_bai_horizontal_layout.setContentsMargins(0, 0, 0, 0)
        self.de_bai_horizontal_layout.setObjectName("de_bai_horizontal_layout")
        self.de_bai_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.de_bai_label.setObjectName("de_bai_label")
        self.de_bai_horizontal_layout.addWidget(self.de_bai_label)
        self.de_bai_text_edit = QtWidgets.QTextEdit(self.horizontalLayoutWidget_2)
        self.de_bai_text_edit.setObjectName("de_bai_text_edit")
        self.de_bai_horizontal_layout.addWidget(self.de_bai_text_edit)
        self.cac_lua_chon_dap_an_label = QtWidgets.QLabel(Frame)
        self.cac_lua_chon_dap_an_label.setGeometry(QtCore.QRect(260, 230, 131, 16))
        self.cac_lua_chon_dap_an_label.setObjectName("cac_lua_chon_dap_an_label")

        self.question_list_widget = QtWidgets.QListWidget(Frame)
        self.question_list_widget.setGeometry(QtCore.QRect(10, 80, 151, 181))
        self.question_list_widget.setObjectName("question_list_widget")

        self.multiple_choice_answer_list_widget = QtWidgets.QListWidget(Frame)
        self.multiple_choice_answer_list_widget.setGeometry(QtCore.QRect(280, 260, 201, 81))
        self.multiple_choice_answer_list_widget.setObjectName("multiple_choice_answer_list_widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(Frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(270, 400, 211, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.chuong_doi_kho_vertical_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.chuong_doi_kho_vertical_layout.setContentsMargins(0, 0, 0, 0)
        self.chuong_doi_kho_vertical_layout.setObjectName("chuong_doi_kho_vertical_layout")
        self.chuong_horizontal_layout = QtWidgets.QHBoxLayout()
        self.chuong_horizontal_layout.setObjectName("chuong_horizontal_layout")
        self.chuong_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.chuong_label.setObjectName("chuong_label")
        self.chuong_horizontal_layout.addWidget(self.chuong_label)
        self.chuong_combo_box = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.chuong_combo_box.setObjectName("chuong_combo_box")
        self.chuong_horizontal_layout.addWidget(self.chuong_combo_box)
        self.chuong_doi_kho_vertical_layout.addLayout(self.chuong_horizontal_layout)
        self.do_kho_horizontal_layout = QtWidgets.QHBoxLayout()
        self.do_kho_horizontal_layout.setObjectName("do_kho_horizontal_layout")
        self.do_kho_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.do_kho_label.setObjectName("do_kho_label")
        self.do_kho_horizontal_layout.addWidget(self.do_kho_label)
        self.do_kho_combo_box = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.do_kho_combo_box.setObjectName("do_kho_combo_box")
        self.do_kho_horizontal_layout.addWidget(self.do_kho_combo_box)
        self.chuong_doi_kho_vertical_layout.addLayout(self.do_kho_horizontal_layout)
        self.xoa_cau_hoi_button = QtWidgets.QPushButton(Frame)
        self.xoa_cau_hoi_button.setGeometry(QtCore.QRect(420, 500, 113, 32))
        self.xoa_cau_hoi_button.setObjectName("xoa_cau_hoi_button")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(Frame)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(280, 350, 201, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.them_chinh_su_xoa_horizontal_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.them_chinh_su_xoa_horizontal_layout.setContentsMargins(0, 0, 0, 0)
        self.them_chinh_su_xoa_horizontal_layout.setObjectName("them_chinh_su_xoa_horizontal_layout")
        self.them_label = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.them_label.setObjectName("them_label")
        self.them_chinh_su_xoa_horizontal_layout.addWidget(self.them_label)
        self.chinh_sua_label = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.chinh_sua_label.setObjectName("chinh_sua_label")
        self.them_chinh_su_xoa_horizontal_layout.addWidget(self.chinh_sua_label)
        self.xoa_label = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.xoa_label.setObjectName("xoa_label")
        self.them_chinh_su_xoa_horizontal_layout.addWidget(self.xoa_label)

        self.save_button = QtWidgets.QPushButton(Frame)
        self.save_button.setGeometry(QtCore.QRect(270, 500, 113, 32))
        self.save_button.setObjectName("save_button")

        self.them_cau_hoi_label = QtWidgets.QLabel(Frame)
        self.them_cau_hoi_label.setGeometry(QtCore.QRect(10, 270, 101, 31))
        self.them_cau_hoi_label.setObjectName("them_cau_hoi_label")

        # POP UP PART
        # Them dap ap pop up
        self.them_dap_an_pop_up = QFrame()
        self.ui_them_dap_an_pop_up = Ui_them_dap_an_pop_up()
        self.ui_them_dap_an_pop_up.setupUi(self.them_dap_an_pop_up)

        # chinh sua dap an pop up
        self.chinh_sua_dap_an_pop_up = QFrame()
        self.ui_chinh_sua_dap_an_pop_up = Ui_chinh_sua_dap_an_pop_up()
        self.ui_chinh_sua_dap_an_pop_up.setupUi(self.chinh_sua_dap_an_pop_up)

        # them cau cau hoi pop up
        self.them_cau_hoi_pop_up = QFrame()
        self.ui_them_cau_hoi_pop_up = Ui_them_cau_hoi_pop_up()
        self.ui_them_cau_hoi_pop_up.setupUi(self.them_cau_hoi_pop_up)

        # handle click
        self.handle_click()
        self.retranslateUi(Frame)

        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.danh_sach_cau_hoi_label.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:24pt;\">Danh sách câu hỏi</span></p></body></html>"))
        self.dang_cau_hoi_label.setText(_translate("Frame", "Dạng câu hỏi"))
        self.trac_nghiem_radio_button.setText(_translate("Frame", "Trắc nghiệm"))
        self.tu_luan_radio_button.setText(_translate("Frame", "Tự luận"))
        self.de_bai_label.setText(_translate("Frame", "Đề bài"))
        self.cac_lua_chon_dap_an_label.setText(_translate("Frame", "Các lựa chọn đáp án"))
        self.chuong_label.setText(_translate("Frame", "Chương"))
        self.do_kho_label.setText(_translate("Frame", "Độ khó"))
        self.xoa_cau_hoi_button.setText(_translate("Frame", "Xóa câu hỏi"))
        self.them_label.setText(_translate("Frame", "<html><head/><body><p><span style=\" text-decoration: underline; color:#0000ff;\">Thêm</span></p></body></html>"))
        self.chinh_sua_label.setText(_translate("Frame", "<html><head/><body><p><span style=\" text-decoration: underline; color:#0000ff;\">Chỉnh sửa</span></p></body></html>"))
        self.xoa_label.setText(_translate("Frame", "<html><head/><body><p><span style=\" text-decoration: underline; color:#fc0107;\">Xóa</span></p></body></html>"))
        self.save_button.setText(_translate("Frame", "Lưu"))
        self.them_cau_hoi_label.setText(_translate("Frame", "<html><head/><body><p><span style=\" text-decoration: underline; color:#0000ff;\">Thêm câu hỏi</span></p></body></html>"))

    def handle_click(self):
        # handle click
        self.question_list_widget.currentRowChanged.connect(self.change_row)
        self.trac_nghiem_radio_button.clicked.connect(self.trac_nghiem_radio_button_click)
        self.tu_luan_radio_button.clicked.connect(self.tu_luan_radio_button_click)
        self.save_button.clicked.connect(self.save_button_click)
        self.xoa_cau_hoi_button.clicked.connect(self.delete_question_click)

        # pop up click
        self.ui_them_dap_an_pop_up.ok_button.clicked.connect(self.them_dap_an_pop_up_ok_button_click)
        self.ui_chinh_sua_dap_an_pop_up.ok_button.clicked.connect(self.chinh_sua_dap_an_pop_up_ok_button_click)
        self.ui_them_cau_hoi_pop_up.ok_button.clicked.connect(self.them_cau_hoi_pop_up_ok_button_click)

        # clickable label
        self.them_label.mousePressEvent = self.them_dap_an_click
        self.chinh_sua_label.mousePressEvent = self.chinh_sua_click
        self.xoa_label.mousePressEvent = self.xoa_click
        self.them_cau_hoi_label.mousePressEvent = self.them_cau_hoi_click
    # ------------------------------------------------------------------------------------------
    # Handle when changing question from question list

    def change_row(self):
        try:
            question = self.question_list_widget.currentItem().text()
            question_id = get_question_id(question)
            self.de_bai_text_edit.setPlainText(question)
            self.multiple_choice_answer_list_widget.clear()
            for answer in get_answer(question_id):
                self.multiple_choice_answer_list_widget.addItem(QtWidgets.QListWidgetItem(answer))
            self.chuong_combo_box.clear()
            self.chuong_combo_box.addItem(get_question_chapter(question))
            self.do_kho_combo_box.clear()
            self.do_kho_combo_box.addItem(get_question_difficulty(question))
        except AttributeError:
            print("Attribute Error")
            pass

    # ------------------------------------------------------------------------------------------
    # Radio button click handle

    def trac_nghiem_radio_button_click(self):
        self.question_list_widget.clear()
        self.de_bai_text_edit.clear()
        for i in get_trac_nghiem_info():
            self.question_list_widget.addItem(QtWidgets.QListWidgetItem(i))

    def tu_luan_radio_button_click(self):
        self.question_list_widget.clear()
        self.de_bai_text_edit.clear()
        for i in get_tu_luan_info():
            self.question_list_widget.addItem(QtWidgets.QListWidgetItem(i))

    # ------------------------------------------------------------------------------------------

    def them_dap_an_click(self, *args, **kwargs):
        self.them_dap_an_pop_up.show()

    def chinh_sua_click(self, *args, **kwargs):
        try:
            question = self.multiple_choice_answer_list_widget.currentItem().text()
            self.ui_chinh_sua_dap_an_pop_up.dap_an_dung_text_edit.setText(question)
            self.chinh_sua_dap_an_pop_up.show()
        except AttributeError:
            pass

    def xoa_click(self, *args, **kwargs):
        answer = self.multiple_choice_answer_list_widget.currentItem().text()
        # remove answer from database
        remove_answer(answer)
        # remove data from ui
        self.multiple_choice_answer_list_widget.takeItem(self.multiple_choice_answer_list_widget.currentRow())

    def save_button_click(self):
        save_mcq_answer_table()
        save_question_table()

    def delete_question_click(self):
        # get text from the question to delete
        question = self.question_list_widget.currentItem().text()
        # remove from ui
        self.question_list_widget.takeItem(self.question_list_widget.currentRow())
        # get question id from question text
        question_id = get_question_id(question)
        # delete all the answer related to the question from the mcq answer table
        delete_all_row(question_id)
        # delete question from question table
        delete_question_from_question_table(question_id)

    def them_cau_hoi_click(self, *args, **kwargs):
        self.them_cau_hoi_pop_up.show()

    # ------------------------------------------------------------------------------------------
    # Pop up event handler

    def chinh_sua_dap_an_pop_up_ok_button_click(self):
        answer = self.multiple_choice_answer_list_widget.currentItem().text()
        new_answer = self.ui_chinh_sua_dap_an_pop_up.dap_an_dung_text_edit.toPlainText()
        # update data
        mcq_answer_table.replace(answer, new_answer, inplace=True)
        # update ui
        self.multiple_choice_answer_list_widget.currentItem().setText(new_answer)
        # close pop up window
        self.chinh_sua_dap_an_pop_up.close()

    def them_dap_an_pop_up_ok_button_click(self):
        # add question to database
        mcq_answer = self.ui_them_dap_an_pop_up.dap_an_dung_text_edit.toPlainText()
        question = self.question_list_widget.currentItem().text()
        question_id = get_question_id(question)
        insert_row(int(question_id), mcq_answer, True)
        # update gui
        self.multiple_choice_answer_list_widget.addItem(mcq_answer)
        # close pop up window
        self.them_dap_an_pop_up.close()

    def them_cau_hoi_pop_up_ok_button_click(self):
        question = self.ui_them_cau_hoi_pop_up.cau_hoi_text_edit.toPlainText()
        # close pop up
        self.them_cau_hoi_pop_up.close()
        # add widget to gui
        self.question_list_widget.addItem(question)

    # ----------------------------------------------------------------------------------------


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
