# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'soan_cau_hoi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from database.Question.question_access import get_trac_nghiem_info, get_tu_luan_info


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(660, 452)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Frame.sizePolicy().hasHeightForWidth())
        Frame.setSizePolicy(sizePolicy)
        Frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        Frame.setAutoFillBackground(False)
        Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(20, 20, 211, 31))
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(260, 20, 271, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dang_cau_hoi_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.dang_cau_hoi_label.setObjectName("dang_cau_hoi_label")
        self.horizontalLayout.addWidget(self.dang_cau_hoi_label)
        self.trac_nghiem_radio_button = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.trac_nghiem_radio_button.setObjectName("trac_nghiem_radio_button")
        self.horizontalLayout.addWidget(self.trac_nghiem_radio_button)
        self.tu_luan_radio_button = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.tu_luan_radio_button.setObjectName("tu_luan_radio_button")
        self.horizontalLayout.addWidget(self.tu_luan_radio_button)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Frame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(260, 80, 251, 131))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.textEdit = QtWidgets.QTextEdit(self.horizontalLayoutWidget_2)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_2.addWidget(self.textEdit)
        self.label_4 = QtWidgets.QLabel(Frame)
        self.label_4.setGeometry(QtCore.QRect(260, 230, 131, 16))
        self.label_4.setObjectName("label_4")
        self.question_list_widget = QtWidgets.QListWidget(Frame)
        self.question_list_widget.setGeometry(QtCore.QRect(10, 80, 151, 181))
        self.question_list_widget.setObjectName("question_list_widget")
        item = QtWidgets.QListWidgetItem()
        self.question_list_widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.question_list_widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.question_list_widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.question_list_widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.question_list_widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.question_list_widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.question_list_widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.question_list_widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.question_list_widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.question_list_widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.question_list_widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.question_list_widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.question_list_widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.question_list_widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.question_list_widget.addItem(item)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:24pt;\">Danh sách câu hỏi</span></p></body></html>"))
        self.dang_cau_hoi_label.setText(_translate("Frame", "Dạng câu hỏi"))
        self.trac_nghiem_radio_button.setText(_translate("Frame", "Trắc nghiệm"))
        self.tu_luan_radio_button.setText(_translate("Frame", "Tự luận"))
        self.label_3.setText(_translate("Frame", "Đề bài"))
        self.label_4.setText(_translate("Frame", "Các lựa chọn đáp án"))
        __sortingEnabled = self.question_list_widget.isSortingEnabled()
        self.question_list_widget.setSortingEnabled(False)
        self.question_list_widget.setSortingEnabled(__sortingEnabled)
        self.question_list_widget.currentRowChanged.connect(self.change_row)
        self.trac_nghiem_radio_button.clicked.connect(self.trac_nghiem_radio_button_click)
        self.tu_luan_radio_button.clicked.connect(self.tu_luan_radio_button_click)

    def change_row(self):
        self.textEdit.setPlainText(self.question_list_widget.currentItem().text())

    def trac_nghiem_radio_button_click(self):
        self.question_list_widget.clear()
        for i in get_trac_nghiem_info():
            item = QtWidgets.QListWidgetItem(i)
            self.question_list_widget.addItem(item)

    def tu_luan_radio_button_click(self):
        self.question_list_widget.clear()
        for i in get_tu_luan_info():
            item = QtWidgets.QListWidgetItem(i)
            self.question_list_widget.addItem(item)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
