# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'them_cau_hoi_pop_up.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_them_cau_hoi_pop_up(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(416, 224)
        Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cau_hoi_label = QtWidgets.QLabel(Frame)
        self.cau_hoi_label.setGeometry(QtCore.QRect(10, 20, 91, 31))
        self.cau_hoi_label.setObjectName("cau_hoi_label")
        self.cau_hoi_text_edit = QtWidgets.QTextEdit(Frame)
        self.cau_hoi_text_edit.setGeometry(QtCore.QRect(20, 60, 361, 121))
        self.cau_hoi_text_edit.setObjectName("cau_hoi_text_edit")
        self.ok_button = QtWidgets.QPushButton(Frame)
        self.ok_button.setGeometry(QtCore.QRect(270, 190, 113, 32))
        self.ok_button.setObjectName("ok_button")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.cau_hoi_label.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Câu hỏi</span></p></body></html>"))
        self.ok_button.setText(_translate("Frame", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_them_cau_hoi_pop_up()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
