QUESTION_PATH = "./database/Question/Question.csv"
MCQ_ANSWER_PATH = "./database/MCQS_Answer/MCQS_Answer.csv"
SUBJECT_PATH = "./database/Subject/Subject.csv"
EXAM_PATH = "./database/Exam/Exam.csv"
EXAM_QUESTION_PATH = "./database/Exam/Exam_Question.csv"
