# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_giao_dien_chinh.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFrame
from gui_giao_dien_chinh.pop_up import Ui_pop_up
from gui_quan_li_mon_hoc.quan_li_mon_hoc import Ui_quan_ly_mon_hoc_frame
from de_thi.quan_li_de_thi import Ui_quan_li_de_thi_frame
from soan_cau_hoi.soan_cau_hoi_ver_trinh_thanh_trung import Ui_soan_cau_hoi_frame
from database.Subject.subject_access import get_subject_id


class Ui_giao_dien_chinh_frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(317, 218)
        Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.soan_cau_hoi_button = QtWidgets.QPushButton(Frame)
        self.soan_cau_hoi_button.setGeometry(QtCore.QRect(10, 30, 291, 41))
        self.soan_cau_hoi_button.setObjectName("soan_cau_hoi_button")
        self.xay_dung_de_thi_button = QtWidgets.QPushButton(Frame)
        self.xay_dung_de_thi_button.setGeometry(QtCore.QRect(10, 90, 291, 41))
        self.xay_dung_de_thi_button.setObjectName("xay_dung_de_thi_button")
        self.quan_li_mon_hoc_button = QtWidgets.QPushButton(Frame)
        self.quan_li_mon_hoc_button.setGeometry(QtCore.QRect(10, 150, 291, 41))
        self.quan_li_mon_hoc_button.setObjectName("quan_li_mon_hoc_button")

        self.soan_cau_hoi_button.clicked.connect(self.soan_cau_hoi_button_click)
        self.xay_dung_de_thi_button.clicked.connect(self.xay_dung_de_thi_button_click)
        self.quan_li_mon_hoc_button.clicked.connect(self.quan_li_mon_hoc_button_click)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.soan_cau_hoi_button.setText(_translate("Frame", "Soạn câu hỏi"))
        self.xay_dung_de_thi_button.setText(_translate("Frame", "Xây dựng đề thi"))
        self.quan_li_mon_hoc_button.setText(_translate("Frame", "Quản lý môn học"))

    def soan_cau_hoi_button_click(self):

        self.pop_up_frame = QFrame()
        self.ui_pop_up = Ui_pop_up()
        self.ui_pop_up.setupUi(self.pop_up_frame)
        self.pop_up_frame.show()
        self.ui_pop_up.ok_button.clicked.connect(self.soan_cau_hoi_pop_up_ok_button_click)

    def soan_cau_hoi_pop_up_ok_button_click(self):
        self.xay_dung_de_thi_frame = QFrame()
        self.ui_xay_dung_de_thi_frame = Ui_soan_cau_hoi_frame()
        self.ui_xay_dung_de_thi_frame.setupUi(self.xay_dung_de_thi_frame,
                                              get_subject_id(self.ui_pop_up.danh_sach_mon_hoc_combo_box.currentText()))
        self.pop_up_frame.close()
        self.xay_dung_de_thi_frame.show()

    def xay_dung_de_thi_button_click(self):
        self.pop_up_frame = QFrame()
        self.ui_pop_up = Ui_pop_up()
        self.ui_pop_up.setupUi(self.pop_up_frame)
        self.pop_up_frame.show()
        self.ui_pop_up.ok_button.clicked.connect(self.xay_dung_de_thi_pop_up_ok_button_click)

    def xay_dung_de_thi_pop_up_ok_button_click(self):
        self.xay_dung_de_thi_frame = QFrame()
        self.ui_xay_dung_de_thi_frame = Ui_quan_li_de_thi_frame()
        self.ui_xay_dung_de_thi_frame.setupUi(self.xay_dung_de_thi_frame,
                                              get_subject_id(self.ui_pop_up.danh_sach_mon_hoc_combo_box.currentText()))
        self.xay_dung_de_thi_frame.show()
        self.pop_up_frame.close()

    def quan_li_mon_hoc_button_click(self):
        self.quan_li_mon_hoc_frame = QFrame()
        self.ui_quan_li_mon_hoc_frame = Ui_quan_ly_mon_hoc_frame()
        self.ui_quan_li_mon_hoc_frame.setupUi(self.quan_li_mon_hoc_frame)
        self.quan_li_mon_hoc_frame.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_giao_dien_chinh_frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
