# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exam_manage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QFrame

from de_thi.exam import Ui_exam_frame
from database.Exam.exam_access import get_last_exam_id, get_exam
from de_thi.tao_de_thi_pop_up import Ui_tao_de_thi_pop_up


class Ui_exam_manage_frame(object):
    def setupUi(self, exam_frame, subject_id):
        self.subject_id = subject_id
        self.Frame = exam_frame
        exam_frame.setObjectName("exam_frame")
        exam_frame.resize(800, 600)
        exam_frame.setAutoFillBackground(False)
        exam_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        exam_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.exam_manage_label = QtWidgets.QLabel(exam_frame)
        self.exam_manage_label.setGeometry(QtCore.QRect(20, 10, 291, 51))
        self.exam_manage_label.setObjectName("exam_manage_label")
        self.open_existing_exam_label = QtWidgets.QLabel(exam_frame)
        self.open_existing_exam_label.setGeometry(QtCore.QRect(30, 60, 151, 41))
        self.open_existing_exam_label.setObjectName("open_existing_exam_label")
        self.create_new_exam_button = QtWidgets.QPushButton(exam_frame)
        self.create_new_exam_button.setGeometry(QtCore.QRect(500, 30, 151, 41))
        self.create_new_exam_button.setStyleSheet("background-color: blue;\n"
"color: white;\n"
"border-radius: 5px;")
        self.create_new_exam_button.setObjectName("create_new_exam_button")
        self.exam_container_frame = QtWidgets.QWidget(exam_frame)
        self.exam_container_frame.setGeometry(QtCore.QRect(20, 100, 760, 400))
        self.exam_container_frame.setStyleSheet(".QWidget  {border-style: dashed;\n"
"border-width: 5px;\n"
"border-color: grey;}")
        self.exam_container_frame.setObjectName("exam_container_frame")
        self.de_thi_button_width = 220
        self.de_thi_button_height = 120
        button_location = [[30, 20], [280, 20], [520, 20], [30, 200], [280, 200], [520, 200]]
        for i, exam_info in enumerate(get_exam(self.subject_id)):
            self.de_thi_button = QtWidgets.QPushButton(self.exam_container_frame)
            self.de_thi_button.setGeometry(QtCore.QRect(button_location[i][0], button_location[i][1],
                                                    self.de_thi_button_width, self.de_thi_button_height))
            self.de_thi_button.setText("{}\n {}".format(exam_info[2], exam_info[3]))
            self.de_thi_button.clicked.connect(lambda state, x=exam_info[0]: self.mo_de_thi_button_click(x))
            self.de_thi_button.setStyleSheet("background-image : url(./canvas_background.jpeg);")

        # there is a bug that this will be washed by garbage collector.
        self.tao_de_thi_moi_button_click = self.tao_de_thi_moi_button_click
        self.create_new_exam_button.clicked.connect(self.tao_de_thi_moi_button_click)
        self.retranslateUi(exam_frame)
        QtCore.QMetaObject.connectSlotsByName(exam_frame)


    def retranslateUi(self, exam_frame):
        _translate = QtCore.QCoreApplication.translate
        exam_frame.setWindowTitle(_translate("exam_frame", "Quản lý đề thi"))
        self.exam_manage_label.setText(_translate("exam_frame", "<html><head/><body><p><span style=\" font-size:24pt;\">Quản lý đề thi</span></p></body></html>"))
        self.open_existing_exam_label.setText(_translate("exam_frame", "<html><head/><body><p><span style=\" font-size:18pt;\">Mở đề thi có sẵn</span></p></body></html>"))
        self.create_new_exam_button.setText(_translate("exam_frame", "Tạo đề thi mới"))

    def tao_de_thi_moi_button_click(self):
        self.tao_de_thi_pop_up = QFrame()
        self.ui_tao_de_thi_pop_up = Ui_tao_de_thi_pop_up()
        self.ui_tao_de_thi_pop_up.setupUi(self.tao_de_thi_pop_up, self.subject_id, self.Frame)
        self.tao_de_thi_pop_up.show()

    def mo_de_thi_button_click(self, exam_id):
        self.ui_chon_cau_hoi_de_dua_vao_de_thi = Ui_exam_frame()
        self.chon_cau_hoi_de_dua_vao_de_thi_frame = QFrame()
        self.ui_chon_cau_hoi_de_dua_vao_de_thi.setupUi(self.chon_cau_hoi_de_dua_vao_de_thi_frame,
                                                       self.subject_id,
                                                       exam_id
                                                       )
        self.chon_cau_hoi_de_dua_vao_de_thi_frame.show()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_exam_manage_frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
