# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quan_li_de_thi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QFrame

from de_thi.chon_cau_hoi_dua_vao_de_thi import ui_chon_cau_hoi_dua_vao_de_thi_frame
from database.Exam.exam_access import get_last_exam_id, get_exam


class Ui_quan_li_de_thi_frame(object):
    def setupUi(self, Frame, subject_id):
        self.subject_id = subject_id
        Frame.setObjectName("Frame")
        Frame.resize(800, 600)
        Frame.setAutoFillBackground(False)
        Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.quan_li_de_thi_label = QtWidgets.QLabel(Frame)
        self.quan_li_de_thi_label.setGeometry(QtCore.QRect(20, 10, 291, 51))
        self.quan_li_de_thi_label.setObjectName("quan_li_de_thi_label")
        self.mo_de_thi_co_san_label = QtWidgets.QLabel(Frame)
        self.mo_de_thi_co_san_label.setGeometry(QtCore.QRect(30, 60, 151, 41))
        self.mo_de_thi_co_san_label.setObjectName("mo_de_thi_co_san_label")
        self.tao_de_thi_moi_button = QtWidgets.QPushButton(Frame)
        self.tao_de_thi_moi_button.setGeometry(QtCore.QRect(500, 30, 151, 41))
        self.tao_de_thi_moi_button.setStyleSheet("background-color: blue;\n"
"color: white;\n"
"border-radius: 5px;")
        self.tao_de_thi_moi_button.setObjectName("tao_de_thi_moi_button")
        self.ngan_hang_de_thi_frame = QtWidgets.QWidget(Frame)
        self.ngan_hang_de_thi_frame.setGeometry(QtCore.QRect(20, 100, 760, 400))
        self.ngan_hang_de_thi_frame.setStyleSheet(".QWidget  {border-style: dashed;\n"
"border-width: 5px;\n"
"border-color: grey;}")
        self.ngan_hang_de_thi_frame.setObjectName("ngan_hang_de_thi_frame")
        self.de_thi_button_width = 220
        self.de_thi_button_height = 120
        button_location = [[30, 20], [280, 20], [520, 20], [30, 200], [280, 200], [520, 200]]
        for i, exam_info in enumerate(get_exam(self.subject_id)):
            self.de_thi_button = QtWidgets.QPushButton(self.ngan_hang_de_thi_frame)
            self.de_thi_button.setGeometry(QtCore.QRect(button_location[i][0], button_location[i][1],
                                                    self.de_thi_button_width, self.de_thi_button_height))
            self.de_thi_button.setText("{}\n {}".format(exam_info[2], exam_info[3]))
            self.de_thi_button.clicked.connect(lambda state, x=exam_info[0]: self.mo_de_thi_button_click(x))
            self.de_thi_button.setStyleSheet("background-image : url(./canvas_background.jpeg);")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)
        self.tao_de_thi_moi_button.clicked.connect(self.tao_de_thi_moi_button_click)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.quan_li_de_thi_label.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:24pt;\">Quản lý đề thi</span></p></body></html>"))
        self.mo_de_thi_co_san_label.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:18pt;\">Mở đề thi có sẵn</span></p></body></html>"))
        self.tao_de_thi_moi_button.setText(_translate("Frame", "Tạo đề thi mới"))

    def tao_de_thi_moi_button_click(self):

        self.ui_chon_cau_hoi_de_dua_vao_de_thi = ui_chon_cau_hoi_dua_vao_de_thi_frame()
        self.chon_cau_hoi_de_dua_vao_de_thi_frame = QFrame()
        self.ui_chon_cau_hoi_de_dua_vao_de_thi.setupUi(self.chon_cau_hoi_de_dua_vao_de_thi_frame,
                                                       self.subject_id,
                                                       get_last_exam_id()
                                                       )
        self.chon_cau_hoi_de_dua_vao_de_thi_frame.show()

    def mo_de_thi_button_click(self, exam_id):
        print(exam_id)
        self.ui_chon_cau_hoi_de_dua_vao_de_thi = ui_chon_cau_hoi_dua_vao_de_thi_frame()
        self.chon_cau_hoi_de_dua_vao_de_thi_frame = QFrame()
        self.ui_chon_cau_hoi_de_dua_vao_de_thi.setupUi(self.chon_cau_hoi_de_dua_vao_de_thi_frame,
                                                       self.subject_id,
                                                       exam_id
                                                       )
        self.chon_cau_hoi_de_dua_vao_de_thi_frame.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_quan_li_de_thi_frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
