# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pop_up.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from database.Subject.subject_access import get_all_subject


class Ui_pop_up(object):
    def setupUi(self, pop_up):
        pop_up.setObjectName("pop_up")
        pop_up.resize(418, 138)
        pop_up.setFrameShape(QtWidgets.QFrame.StyledPanel)
        pop_up.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chon_mon_hoc_label = QtWidgets.QLabel(pop_up)
        self.chon_mon_hoc_label.setGeometry(QtCore.QRect(40, 20, 111, 31))
        self.chon_mon_hoc_label.setObjectName("chon_mon_hoc_label")
        self.danh_sach_mon_hoc_combo_box = QtWidgets.QComboBox(pop_up)
        self.danh_sach_mon_hoc_combo_box.setGeometry(QtCore.QRect(160, 20, 221, 31))
        self.danh_sach_mon_hoc_combo_box.setObjectName("danh_sach_mon_hoc_combo_box")

        for subject in get_all_subject():
            self.danh_sach_mon_hoc_combo_box.addItem(subject)
        self.ok_button = QtWidgets.QPushButton(pop_up)
        self.ok_button.setGeometry(QtCore.QRect(140, 70, 161, 41))
        self.ok_button.setObjectName("ok_button")

        self.retranslateUi(pop_up)
        QtCore.QMetaObject.connectSlotsByName(pop_up)

    def retranslateUi(self, pop_up):
        _translate = QtCore.QCoreApplication.translate
        pop_up.setWindowTitle(_translate("pop_up", "Frame"))
        self.chon_mon_hoc_label.setText(_translate("pop_up", "Chọn môn học:"))
        self.ok_button.setText(_translate("pop_up", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    pop_up = QtWidgets.QFrame()
    ui = Ui_pop_up()
    ui.setupUi(pop_up)
    pop_up.show()
    sys.exit(app.exec_())
