# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chon_cau_hoi_dua_vao_de_thi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from database.Question.question_access import get_info, get_tu_luan_info, get_trac_nghiem_info, get_question_chapter
from database.Question.question_access import get_question_id, get_question_difficulty
from database.MCQS_Answer.mcqs_access import get_answer, get_right_answer
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(885, 581)
        Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.question_list_widget = QtWidgets.QListWidget(Frame)
        self.question_list_widget.setGeometry(QtCore.QRect(40, 60, 301, 301))
        self.question_list_widget.setObjectName("question_list_widget")
        self.question_show_text_edit = QtWidgets.QTextEdit(Frame)
        self.question_show_text_edit.setGeometry(QtCore.QRect(370, 60, 411, 301))
        self.question_show_text_edit.setObjectName("question_show_text_edit")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 390, 261, 21))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tat_ca_radio_button = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.tat_ca_radio_button.setObjectName("tat_ca_radio_button")
        self.horizontalLayout.addWidget(self.tat_ca_radio_button)
        self.trac_nghiem_radio_button = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.trac_nghiem_radio_button.setObjectName("trac_nghiem_radio_button")
        self.horizontalLayout.addWidget(self.trac_nghiem_radio_button)
        self.tu_luan_radio_button = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.tu_luan_radio_button.setObjectName("tu_luan_radio_button")
        self.horizontalLayout.addWidget(self.tu_luan_radio_button)
        self.dang_cau_hoi_label = QtWidgets.QLabel(Frame)
        self.dang_cau_hoi_label.setGeometry(QtCore.QRect(40, 370, 79, 15))
        self.dang_cau_hoi_label.setObjectName("dang_cau_hoi_label")

        self.trac_nghiem_radio_button.clicked.connect(self.trac_nghiem_button_click)
        self.tu_luan_radio_button.clicked.connect(self.tu_luan_button_click)
        self.tat_ca_radio_button.clicked.connect(self.tat_ca_button_click)

        self.question_list_widget.currentRowChanged.connect(self.change_row)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.question_show_text_edit.setHtml(_translate("Frame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">grjdfhkgbodfwkgjierwgijerqhjgjierbg</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">rgkjrdkghdergn</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">rghhjregkhlrerh</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">herjhlrekghj</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">rhjkrethre</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">erhjrekgjwae</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">rgrjeshrilsg</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">rejerkhrew</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">reg</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">gt</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">g</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">g</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">g</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">g</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">g</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">g</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">g</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">g</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">g</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">g</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">gfd</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">gfdh</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">fdh</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">fgh</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">gf</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">jfg</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">hj</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">gj</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ghjh</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">gj</p></body></html>"))
        self.tat_ca_radio_button.setText(_translate("Frame", "Tất cả"))
        self.trac_nghiem_radio_button.setText(_translate("Frame", "Trắc nghiệm"))
        self.tu_luan_radio_button.setText(_translate("Frame", "Tự luận"))
        self.dang_cau_hoi_label.setText(_translate("Frame", "Dạng câu hỏi"))

    def trac_nghiem_button_click(self):
        self.question_list_widget.clear()
        for i in get_trac_nghiem_info():
            self.question_list_widget.addItem(QtWidgets.QListWidgetItem(i))

    def tu_luan_button_click(self):
        self.question_list_widget.clear()
        for i in get_tu_luan_info():
            self.question_list_widget.addItem(QtWidgets.QListWidgetItem(i))

    def tat_ca_button_click(self):
        self.question_list_widget.clear()
        for i in get_info():
            self.question_list_widget.addItem(QtWidgets.QListWidgetItem(i))

    def change_row(self):
        try:
            self.question_show_text_edit.clear()
            question = self.question_list_widget.currentItem().text()
            question_id = get_question_id(question)
            list_answer = get_answer(question_id)
            self.question_show_text_edit.append(question)
            for number, answer in enumerate(list_answer):
                self.question_show_text_edit.append("{}.  {}".format(number, answer))
            self.question_show_text_edit.append("Thông tin chi tiết:")
            self.question_show_text_edit.append("Đáp án đúng: {}".format(get_right_answer(question_id)))
            self.question_show_text_edit.append("Độ khó: {}".format(get_question_difficulty(question_id)))
            self.question_show_text_edit.append("Chương: Chương {}".format(get_question_chapter(question_id)))

            # self.multiple_choice_answer_list_widget.clear()
            # for i in get_answer(question):
            #     item = QtWidgets.QListWidgetItem(i)
            #     self.multiple_choice_answer_list_widget.addItem(item)
            # self.chuong_combo_box.clear()
            # self.chuong_combo_box.addItem(get_question_chapter(question))
            # self.do_kho_combo_box.clear()
            # self.do_kho_combo_box.addItem(get_question_difficulty(question))
        except AttributeError:
            print("Attribute Error")
            pass


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
