# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modify_answer_pop_up.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_modify_answer_pop_up(object):
    def setupUi(self, modify_answer_pop_up):
        modify_answer_pop_up.setObjectName("modify_answer_pop_up")
        modify_answer_pop_up.resize(379, 201)
        modify_answer_pop_up.setFrameShape(QtWidgets.QFrame.StyledPanel)
        modify_answer_pop_up.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalLayout = QtWidgets.QVBoxLayout(modify_answer_pop_up)
        self.verticalLayout.setObjectName("verticalLayout")
        self.answer_label = QtWidgets.QLabel(modify_answer_pop_up)
        self.answer_label.setObjectName("answer_label")
        self.verticalLayout.addWidget(self.answer_label)
        self.answer_text_edit = QtWidgets.QTextEdit(modify_answer_pop_up)
        self.answer_text_edit.setObjectName("answer_text_edit")
        self.verticalLayout.addWidget(self.answer_text_edit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.right_answer_check_box = QtWidgets.QCheckBox(modify_answer_pop_up)
        self.right_answer_check_box.setText("")
        self.right_answer_check_box.setObjectName("right_answer_check_box")
        self.horizontalLayout.addWidget(self.right_answer_check_box)
        self.right_answer_label = QtWidgets.QLabel(modify_answer_pop_up)
        self.right_answer_label.setObjectName("right_answer_label")
        self.horizontalLayout.addWidget(self.right_answer_label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.ok_button = QtWidgets.QPushButton(modify_answer_pop_up)
        self.ok_button.setObjectName("ok_button")
        self.verticalLayout.addWidget(self.ok_button)

        self.retranslateUi(modify_answer_pop_up)
        QtCore.QMetaObject.connectSlotsByName(modify_answer_pop_up)

    def retranslateUi(self, modify_answer_pop_up):
        _translate = QtCore.QCoreApplication.translate
        modify_answer_pop_up.setWindowTitle(_translate("modify_answer_pop_up", "Chỉnh sửa đáp án"))
        self.answer_label.setText(_translate("modify_answer_pop_up", "Đáp án"))
        self.right_answer_label.setText(_translate("modify_answer_pop_up", "Đáp án đúng"))
        self.ok_button.setText(_translate("modify_answer_pop_up", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    modify_answer_pop_up = QtWidgets.QFrame()
    ui = Ui_modify_answer_pop_up()
    ui.setupUi(modify_answer_pop_up)
    modify_answer_pop_up.show()
    sys.exit(app.exec_())
