# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tao_de_thi_pop_up.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFrame

from database.Exam.exam_access import get_last_exam_id
from gui_exam.exam import Ui_exam_frame
from gui_exam.ra_de_thi_tu_dong import Ui_ra_de_thi_tu_dong_frame


class Ui_tao_de_thi_pop_up(object):
    def setupUi(self, Frame, subject_id, parent_frame):
        self.parent_frame = parent_frame
        self.subject_id = subject_id
        self.Frame = Frame
        Frame.setObjectName("Frame")
        Frame.resize(361, 179)
        Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalLayoutWidget = QtWidgets.QWidget(Frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 20, 271, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tao_de_thi_thu_cong_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.tao_de_thi_thu_cong_button.setObjectName("tao_de_thi_thu_cong_button")
        self.verticalLayout.addWidget(self.tao_de_thi_thu_cong_button)
        self.tao_de_thi_tu_dong_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.tao_de_thi_tu_dong_button.setObjectName("tao_de_thi_tu_dong_button")
        self.verticalLayout.addWidget(self.tao_de_thi_tu_dong_button)

        self.tao_de_thi_thu_cong_button.clicked.connect(self.tao_de_thi_thu_cong_button_click)
        self.tao_de_thi_tu_dong_button.clicked.connect(self.tao_de_thi_tu_dong_button_click)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Tạo đề thi"))
        self.tao_de_thi_thu_cong_button.setText(_translate("Frame", "Tạo đề thi thủ công"))
        self.tao_de_thi_tu_dong_button.setText(_translate("Frame", "Tạo đề thi tự động"))

    def tao_de_thi_thu_cong_button_click(self):
        self.ui_chon_cau_hoi_de_dua_vao_de_thi = Ui_exam_frame()
        self.chon_cau_hoi_de_dua_vao_de_thi_frame = QFrame()
        self.ui_chon_cau_hoi_de_dua_vao_de_thi.setupUi(self.chon_cau_hoi_de_dua_vao_de_thi_frame,
                                                       self.subject_id,
                                                       get_last_exam_id()
                                                       )
        self.chon_cau_hoi_de_dua_vao_de_thi_frame.show()
        self.Frame.close()
        self.parent_frame.close()

    def tao_de_thi_tu_dong_button_click(self):
        self.ui_ra_de_thi_tu_dong = Ui_ra_de_thi_tu_dong_frame()
        self.ra_de_thi_tu_dong_frame = QFrame()
        self.ui_ra_de_thi_tu_dong.setupUi(self.ra_de_thi_tu_dong_frame, self.subject_id)
        self.ra_de_thi_tu_dong_frame.show()
        self.Frame.close()
        self.parent_frame.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_tao_de_thi_pop_up()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
